name: MailBox
version: 0.8
depend: [SmartInvs]
description: Envoyer et recevoir des objets et des mails.
author: Bletrazer
api-version: 1.13
main: fr.bletrazer.mailbox.Main
commands:
  mailbox:
    description: commande du plugin.
    
permissions:
  mailbox.admin:
    description: Toutes les permissions du plugin.
    default: op
    children:
     - mailbox.openmenu.*
     - mailbox.letter.*
     - mailbox.item.*
     - mailbox.check.*
     
  mailbox.openmenu.*:
    description: Permission d'ouvrir toutes les boîtes de récéptions.
    children:
     - mailbox.openmenu.self
     - mailbox.openmenu.other
  mailbox.openmenu.self:
    description: Permission d'ouvrir sa propre boîte de récéption.
    default: true
  mailbox.openmenu.other:
    description: Permission d'ouvrir la boîte de récéption des autres joueurs.
    
  mailbox.letter.*:
    description: Permissions d'envoyer, de répondre et de lire les lettres.
    children:
     - mailbox.letter.delete.*
     - mailbox.letter.reply.*
     - mailbox.letter.send.*
     - mailbox.letter.read.*
     - mailbox.letter.markall.*
     
  mailbox.letter.delete.*:
    description: Permissions pour supprimer des lettres.
    children:
     - mailbox.letter.delete.self
     - mailbox.letter.delete.other
  mailbox.letter.delete.self:
    default: true
    description: Permission de supprimer des lettre de sa boite.
  mailbox.letter.delete.other:
    description: Permission de supprimer des lettre de la boite d'un autre joueur.
  mailbox.letter.reply.*:
    description: Permission de répondre a une lettre.
    children:
     - mailbox.letter.reply.self
     - mailbox.letter.reply.other
  mailbox.letter.reply.self:
    description: Permission de répondre a une lettre dont vous êtes le destinataire.
    default: true
  mailbox.letter.reply.other:
    description: Permission de répondre a une lettre dont vous n'êtes pas le destinataire.
  mailbox.letter.read.*:
    description: Permissions de lire les lettres.
    children:
     - mailbox.letter.read.self
     - mailbox.letter.read.other
  mailbox.letter.read.self:
    description: Permission de lire ses lettres reçues.
    default: true
  mailbox.letter.read.other:
    description: Permission de lire les lettre reçu par d'autres joueurs.
  mailbox.letter.markall.*:
    description: Permission de marquer des lettres comme ayant été lues.
    children:
     - mailbox.letter.markall.self
     - mailbox.letter.markall.other
  mailbox.letter.markall.self:
    description: Permission de marquer ses lettres comme ayant été lues.
  mailbox.letter.markall.other:
    description: Permission de marquer les lettres d'autres joueurs comme ayant été lues.
  
  mailbox.item.*:
    description: Permission d'envoyer, de supprimer et de recupérer des objets.
    children:
     - mailbox.item.send
     - mailbox.item.recover
     - mailbox.item.delete
  mailbox.item.send:
    description: Permission d'envoyer des objets
  mailbox.item.recover.*:
    description: Permission de recuperer les objets des boites.
    children:
     - mailbox.recover.item.self
     - mailbox.recover.item.other
  mailbox.item.recover.self:
    description: Permission de recuperer ses objets de sa boite d'objet
    default: true
  mailbox.item.recover.other:
    description: Permission de recuperer les objets dans la boite de reception d'autres joueurs.
  mailbox.item.delete.*:
    description: Permissions pour supprimer des objets
    children:
     - mailbox.item.delete.self
     - mailbox.item.delete.other
  mailbox.item.delete.self:
    description: Permission de supprimer ses objets de sa boîte de récéption d'objets.
  mailbox.item.delete.other:
    description: permission de supprimer des objets de la boîte de récéption d'autres joueurs.
  mailbox.check.*:
    description: Permissions de demander l'état des boîtes de récéptions.
    children:
     - mailbox.check.self
     - mailbox.check.other
  mailbox.check.self:
    description: Permission de demander l'état de sa boîte de récéption.
  mailbox.check.other:
    description: Permission de demander l'état de la boîte de récéption d'autres joueurs.
    
  mailbox.send.*:
    description: Permissions pour les choix des cibles.
    children:
     - mailbox.send.standard
     - mailbox.send.announce
  mailbox.send.announce:
    description: Permission d'envoyer une lettre a plusieurs destinataires à la fois.
  mailbox.send.standard:
    description: Permission d'effectuer un envoie.
    default: true