name: MailBox
version: 0.1a
depend: [SmartInvs]
description: Envoyer et recevoir des objets et des mails.
author: Bletrazer
api-version: 1.13
main: fr.bletrazer.mailbox.Main
commands:
  mailbox:
    description: commande par defaut
    permission: mailbox.admin